# Language model config

lm_config:
  name: ESM
  cache_dir: /nfs/lambda_stor_01/homes/khippe/github/biolab/cache
  pretrained_model_name_or_path: facebook/esm2_t30_150M_UR50D
  half_precision: true
  eval_model: true

  tokenizer_config:
    max_length: 1024

  dataloader_config:
    batch_size: 64


# List of task configurations
task_configs:
  - name: DNAClassification
    dataset_name_or_path: ./examples/dna_classification
    output_transform: average_pool
    target_col: label
    # target_col: coding
    metrics: [accuracy, f1]
    balance_classes: true
    max_samples: 2000

  - name: GCContent
    dataset_name_or_path: ./examples/small_mdh_gc
    output_transform: average_pool
    metrics: [mse, rmse, r2]
