lm_config:
  name: GenSLM-ESM
  checkpoint_path: /nfs/lambda_stor_01/homes/khippe/genslm_foundation/pre_training/genslm-contrastive/patric_prod/patric_joint_150m/checkpoint-135000
  tokenizer_path: /nfs/lambda_stor_01/homes/khippe/github/genslm-esm/tokenizer_esm_genslm
  half_precision: true
  eval_mode: true

  dataloader_config:
    batch_size: 64


# Task configurations
task_configs:
  - name: DNAClassification
    dataset_name_or_path: ./examples/dna_classification
    target_col: coding
    # target_col: label
    metrics: [accuracy, f1]
    balance_classes: true
    max_samples: 2000

  - name: GCContent
    dataset_name_or_path: ./examples/small_mdh_gc
    metrics: [mse, rmse, r2]
