# Language model config
output_dir: ./individualinit-parsl-test

parsl_config:
  name: singlenode
  available_accelerators: 4

lm_config:
  name: ESM
  cache_dir: /lus/eagle/projects/FoundEpidem/hippekp/github/biolab/hfcache
  pretrained_model_name_or_path: facebook/esm2_t33_650M_UR50D
  half_precision: true
  eval_mode: true

  tokenizer_config:
    max_length: 1024

  dataloader_config:
    batch_size: 64


# List of task configurations
task_configs:
  #### Biolab data ####
  - name: DNAClassification
    dataset_name_or_path: /lus/eagle/projects/FoundEpidem/hippekp/biolab-evals/biolab-data/dna_classification
    balance_classes: true
    max_samples: 1000

  - name: GCContent
    dataset_name_or_path: /lus/eagle/projects/FoundEpidem/hippekp/biolab-evals/biolab-data/small_mdh_gc
    metrics: [mse, rmse, r2]
    max_samples: 1000

  - name: PatricSecondaryStructureClassification
    dataset_name_or_path: /lus/eagle/projects/FoundEpidem/hippekp/biolab-evals/biolab-data/patric_secondary_structure_classification
    max_samples: 1000

  #### CaLM Tasks ####
  - name: CaLM-Meltome
    max_samples: 1000
    dataset_name_or_path: /lus/eagle/projects/FoundEpidem/hippekp/biolab-evals/biolab-data/CaLM-meltome

  - name: CaLM-Solubility
    max_samples: 1000
    dataset_name_or_path: /lus/eagle/projects/FoundEpidem/hippekp/biolab-evals/biolab-data/CaLM-Solubility
