# Language model config

lm_config:
  name: ESM
  cache_dir: /nfs/lambda_stor_01/homes/khippe/github/biolab/cache
  pretrained_model_name_or_path: facebook/esm2_t33_650M_UR50D
  half_precision: true
  eval_mode: true

  tokenizer_config:
    max_length: 1024

  dataloader_config:
    batch_size: 64


# List of task configurations
task_configs:
  - name: DNAClassification
    dataset_name_or_path: ./examples/dna_classification
    target_col: label
    # target_col: coding
    metrics: [accuracy, f1]
    balance_classes: true
    max_samples: 200
  - name: GCContent
    dataset_name_or_path: ./examples/small_mdh_gc
    metrics: [mse, rmse, r2]
  - name: PatricSecondaryStructureClassification
    dataset_name_or_path: ./examples/patric_secondary_structure_classification
    max_samples: 200

  - name: CaLM-Meltome
    max_samples: 200
  - name: CaLM-Solubility
    max_samples: 200

  - name: GUEEMP
    dataset_name_or_path: /nfs/lambda_stor_01/homes/khippe/genslm_foundation/downstream_evaluation/biolab-data/GUE-dnabert2/hf-GUE/EMP/H3-hf
    max_samples: 200
  - name: GUESpliceSiteDetection
    dataset_name_or_path: /nfs/lambda_stor_01/homes/khippe/genslm_foundation/downstream_evaluation/biolab-data/GUE-dnabert2/hf-GUE/splice/reconstructed-hf
    max_samples: 200
